// Generated by CoffeeScript 1.9.2
var mai;

mai = function() {
  var btns, buy, e;
  buy = $('#J_juValid .J_LinkBuy');
  try {
    $('a#J_LinkBuy')[0].click();
    console.log($('a#J_LinkBuy')[0]);
  } catch (_error) {
    e = _error;
    e;
  }
  try {
    $('a.go-btn')[0].click();
    console.log($('a.go-btn')[0]);
  } catch (_error) {
    e = _error;
    e;
  }
  console.log('1111');
  btns = $('a#J_LinkBuy');
  if ($('div.tb-btn-wait') && $('div.tb-btn-wait')[0]) {
    return window.location.reload();
  }
};

mai();

setInterval(mai, 500);

//# sourceMappingURL=reload.js.map
